name: Scheduled Standings Update

on:
  schedule:
    - cron: '0 21 * * 6,0'
      timezone: "Asia/Manila"
    - cron: '0 23 * * 6,0'
      timezone: "Asia/Manila"
    - cron: '0 1 * * 0,1'
      timezone: "Asia/Manila"
    - cron: '0 3 * * 0,1'
      timezone: "Asia/Manila"
    - cron: '0 5 * * *'
      timezone: "Asia/Manila"

jobs:
  trigger-edge-function:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Supabase Edge Function
      run: |
        curl -L -X POST "https://hsgqhgtdcyypxrvmpxmx.supabase.co/functions/v1/update-Top-Standing" \
          -H "apikey: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          -H "Content-Type: application/json" \
          --data '{"name":"Functions"}'
